apiVersion: apps/v1
kind: Deployment
metadata:
  name: ami-dep
  namespace: group07
  labels:
    app: ami-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ami-dep
  template: 
    metadata:
      labels:
        app: ami-dep
    spec:          
      containers:
        - name: ami
          image: gitlab.ldv.ei.tum.de:5005/ami2022/group07
          ports:
            - containerPort: 8888  #8888
      imagePullSecrets:
        - name: regcredupdated

---
apiVersion: v1
kind: Service
metadata:
  name: ami-service
  namespace: group07 
spec:
  selector:
    app: ami-dep
  type: NodePort  
  ports:
  - protocol: TCP
    port: 8888 
    targetPort: 8888    #8888
    nodePort: 30700
